DELETE FROM listing_amenities;
DELETE FROM listing_images;
DELETE FROM bookings;
DELETE FROM reviews;
DELETE FROM listings;
DELETE FROM cities;
DELETE FROM users;

INSERT INTO cities (id, name, country, description, image_url) VALUES
                                                                   (1, 'Ohrid', 'North Macedonia', 'Lakeside old town known for churches, clear water, and mountain views.', 'https://images.pexels.com/photos/2031706/pexels-photo-2031706.jpeg'),
                                                                   (2, 'Skopje', 'North Macedonia', 'Capital city with Ottoman bazaars, riverside squares, and quick mountain access.', 'https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg'),
                                                                   (3, 'Mavrovo', 'North Macedonia', 'National park village for lake weekends, hiking, and winter stays.', 'https://images.pexels.com/photos/753626/pexels-photo-753626.jpeg'),
                                                                   (4, 'Belgrade', 'Serbia', 'Danube and Sava river city with nightlife, historic neighborhoods, and modern apartments.', 'https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg'),
                                                                   (5, 'Kopaonik', 'Serbia', 'Mountain resort destination with ski slopes, forest trails, and chalet stays.', 'https://images.pexels.com/photos/1438832/pexels-photo-1438832.jpeg'),
                                                                   (6, 'Dubrovnik', 'Croatia', 'Adriatic walled city with stone streets, sea views, and historic apartments.', 'https://images.pexels.com/photos/1036857/pexels-photo-1036857.jpeg'),
                                                                   (7, 'Split', 'Croatia', 'Coastal city built around Diocletian palace with beaches and ferry links.', 'https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg'),
                                                                   (8, 'Budva', 'Montenegro', 'Montenegrin beach town with an old town, coves, and sea-view villas.', 'https://images.pexels.com/photos/594077/pexels-photo-594077.jpeg'),
                                                                   (9, 'Kotor', 'Montenegro', 'Bay town surrounded by mountains, stone houses, and waterfront promenades.', 'https://images.pexels.com/photos/2090645/pexels-photo-2090645.jpeg'),
                                                                   (10, 'Sarajevo', 'Bosnia and Herzegovina', 'Historic city with Ottoman streets, mountain views, and cafe culture.', 'https://images.pexels.com/photos/584399/pexels-photo-584399.jpeg'),
                                                                   (11, 'Mostar', 'Bosnia and Herzegovina', 'Neretva river city centered on the old bridge and stone old town.', 'https://images.pexels.com/photos/4508644/pexels-photo-4508644.jpeg'),
                                                                   (12, 'Ksamil', 'Albania', 'Ionian beach village known for turquoise water and island views.', 'https://images.pexels.com/photos/338504/pexels-photo-338504.jpeg'),
                                                                   (13, 'Tirana', 'Albania', 'Colorful capital with cafes, museums, and quick access to Dajti mountain.', 'https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg'),
                                                                   (14, 'Bansko', 'Bulgaria', 'Mountain town with ski access, old stone streets, and alpine apartments.', 'https://images.pexels.com/photos/3551230/pexels-photo-3551230.jpeg'),
                                                                   (15, 'Thessaloniki', 'Greece', 'Northern Greek city with waterfront walks, food markets, and Roman history.', 'https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg'),
                                                                   (16, 'Lefkada', 'Greece', 'Ionian island destination with blue beaches, cliffs, and villa stays.', 'https://images.pexels.com/photos/189296/pexels-photo-189296.jpeg'),
                                                                   (17, 'Kicevo', 'North Macedonia', 'Small town known for clear water, and mountain views.', 'https://photos.wikimapia.org/p/00/01/65/27/39_big.jpg');


INSERT INTO users (id, first_name, last_name, email, password, phone_number, profile_picture, role, is_active) VALUES
                                                                                                                   (1, 'Airbnb', 'Host', 'host@airbnb.com', '$2a$10$0TVMtK6ZJUB.Vvpc8vFrAeT0bbHab/PU.lLpzin9v6M3Da3sZRO.G', '+38970123456', 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg', 'HOST', true),
                                                                                                                   (2, 'Mila', 'Petrova', 'mila@example.com', '$2a$10$0TVMtK6ZJUB.Vvpc8vFrAeT0bbHab/PU.lLpzin9v6M3Da3sZRO.G', '+38970222333', 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg', 'GUEST', true),
                                                                                                                   (3, 'Stefan', 'Ilic', 'stefan@example.com', '$2a$10$0TVMtK6ZJUB.Vvpc8vFrAeT0bbHab/PU.lLpzin9v6M3Da3sZRO.G', '+38164111222', 'https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg', 'GUEST', true),
                                                                                                                   (4, 'Elena', 'Kosta', 'elena@example.com', '$2a$10$0TVMtK6ZJUB.Vvpc8vFrAeT0bbHab/PU.lLpzin9v6M3Da3sZRO.G', '+35569222333', 'https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg', 'GUEST', true),
                                                                                                                   (5, 'Ana', 'Jovanovic', 'ana@example.com', '$2a$10$0TVMtK6ZJUB.Vvpc8vFrAeT0bbHab/PU.lLpzin9v6M3Da3sZRO.G', '+38164555111', 'https://images.pexels.com/photos/1858175/pexels-photo-1858175.jpeg', 'GUEST', true),
                                                                                                                   (6, 'Marko', 'Nikolic', 'marko@example.com', '$2a$10$0TVMtK6ZJUB.Vvpc8vFrAeT0bbHab/PU.lLpzin9v6M3Da3sZRO.G', '+38166777222', 'https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg', 'GUEST', true);

INSERT INTO listings (id, title, description, price_per_night, max_guests, category, city_id, host_id, is_available, bedrooms, bathrooms) VALUES
                                                                                                                                              (1, 'Old Town Ohrid Stone House', 'Restored stone house above the lake, walking distance to Kaneo, Plaosnik, and the old bazaar.', 115.00, 4, 'HOUSE', 1, 1, true, 2, 1),
                                                                                                                                              (2, 'Ohrid Lakefront Studio', 'Compact studio with a balcony facing the lake and easy access to the promenade.', 72.00, 2, 'STUDIO', 1, 1, true, 1, 1),
                                                                                                                                              (3, 'Skopje Riverside Loft', 'Modern loft near the Vardar river, Macedonia Square, and the Old Bazaar.', 68.00, 3, 'LOFT', 2, 1, true, 1, 1),
                                                                                                                                              (4, 'Mavrovo Pine Cabin', 'Warm cabin near the lake with a fireplace, forest views, and space for hiking gear.', 125.00, 6, 'CABIN', 3, 1, true, 3, 2),
                                                                                                                                              (5, 'Belgrade Waterfront Apartment', 'Bright apartment close to Savamala, river walks, restaurants, and public transport.', 105.00, 4, 'APARTMENT', 4, 1, true, 2, 1),
                                                                                                                                              (6, 'Kopaonik Ski Chalet', 'Slope-ready chalet with sauna, boot storage, and mountain views from the living room.', 155.00, 6, 'CABIN', 5, 1, true, 3, 2),
                                                                                                                                              (7, 'Dubrovnik Old Walls Apartment', 'Stone apartment inside the old city, close to Stradun, city walls, and swimming spots.', 210.00, 4, 'APARTMENT', 6, 1, true, 2, 1),
                                                                                                                                              (8, 'Split Palace Studio', 'Studio tucked near Diocletian palace with a quiet courtyard and quick access to the Riva.', 145.00, 2, 'STUDIO', 7, 1, true, 1, 1),
                                                                                                                                              (9, 'Budva Sea View Villa', 'Villa above Budva with terraces, sea views, and a short drive to Mogren beach.', 240.00, 7, 'VILLA', 8, 1, true, 4, 3),
                                                                                                                                              (10, 'Kotor Bay Guesthouse', 'Traditional guesthouse with bay views, stone details, and access to the old town trail.', 130.00, 5, 'GUESTHOUSE', 9, 1, true, 2, 2),
                                                                                                                                              (11, 'Sarajevo Bascarsija Loft', 'Loft near the old bazaar with exposed brick, city views, and cafes around the corner.', 82.00, 3, 'LOFT', 10, 1, true, 1, 1),
                                                                                                                                              (12, 'Mostar Bridge View Apartment', 'Apartment overlooking the Neretva river and old bridge, with a shaded terrace.', 88.00, 4, 'APARTMENT', 11, 1, true, 2, 1),
                                                                                                                                              (13, 'Ksamil Turquoise Villa', 'Relaxed villa near the beach with outdoor dining, sea colors, and parking included.', 135.00, 5, 'VILLA', 12, 1, true, 2, 2),
                                                                                                                                              (14, 'Tirana Skyline Flat', 'Central flat with balcony views, close to Blloku, Skanderbeg Square, and cafes.', 64.00, 4, 'APARTMENT', 13, 1, true, 2, 1),
                                                                                                                                              (15, 'Bansko Alpine Penthouse', 'Penthouse near the gondola with mountain views, heating, and ski storage.', 96.00, 5, 'LOFT', 14, 1, true, 2, 2),
                                                                                                                                              (16, 'Thessaloniki Waterfront Apartment', 'Apartment near the White Tower and waterfront, ideal for food and culture weekends.', 112.00, 4, 'APARTMENT', 15, 1, true, 2, 1),
                                                                                                                                              (17, 'Lefkada Blue Villa', 'Villa with terraces, sea views, and easy drives to Porto Katsiki and Kathisma beach.', 260.00, 6, 'VILLA', 16, 1, true, 3, 3),
                                                                                                                                              (18, 'Ohrid Family Guesthouse', 'Family-friendly guesthouse in a quiet Ohrid neighborhood with garden seating and parking.', 95.00, 6, 'GUESTHOUSE', 1, 1, true, 3, 2),
                                                                                                                                              (19, 'Ohrid Bazaar Loft', 'Loft above the old bazaar with exposed stone walls and a short walk to the lake.', 78.00, 3, 'LOFT', 1, 1, true, 1, 1),
                                                                                                                                              (20, 'Skopje City Center Apartment', 'Central apartment steps from Macedonia Square and the pedestrian boulevard.', 74.00, 4, 'APARTMENT', 2, 1, true, 2, 1),
                                                                                                                                              (21, 'Skopje Fortress View Studio', 'Small studio with views toward Kale fortress and quick access to cafes.', 55.00, 2, 'STUDIO', 2, 1, true, 1, 1),
                                                                                                                                              (22, 'Mavrovo Lakeside Cottage', 'Cozy cottage near Mavrovo lake with a wood stove and mountain trail access.', 108.00, 4, 'COTTAGE', 3, 1, true, 2, 1),
                                                                                                                                              (23, 'Belgrade Skadarlija Loft', 'Loft in the bohemian quarter with exposed beams and easy walks to Kalemegdan.', 90.00, 3, 'LOFT', 4, 1, true, 1, 1),
                                                                                                                                              (24, 'Belgrade New Belgrade Apartment', 'Spacious apartment with river views and quick tram access to downtown.', 98.00, 5, 'APARTMENT', 4, 1, true, 3, 2),
                                                                                                                                              (25, 'Kopaonik Forest Cabin', 'Secluded cabin near the pistes with a wood-burning stove and forest views.', 140.00, 4, 'CABIN', 5, 1, true, 2, 1),
                                                                                                                                              (26, 'Dubrovnik Lapad Villa', 'Villa in the quiet Lapad peninsula with a pool and short walk to the beach.', 275.00, 8, 'VILLA', 6, 1, true, 4, 3),
                                                                                                                                              (27, 'Split Marjan Hill Apartment', 'Apartment near Marjan forest park with sea glimpses and a shaded terrace.', 118.00, 4, 'APARTMENT', 7, 1, true, 2, 1),
                                                                                                                                              (28, 'Split Diocletian Guesthouse', 'Traditional guesthouse steps from the palace basement halls and the fish market.', 102.00, 4, 'GUESTHOUSE', 7, 1, true, 2, 2),
                                                                                                                                              (29, 'Budva Old Town Studio', 'Compact studio inside the old town walls, close to the citadel and beaches.', 89.00, 2, 'STUDIO', 8, 1, true, 1, 1),
                                                                                                                                              (30, 'Kotor Old Town House', 'Stone house within the city walls, close to the cathedral and cat museum.', 165.00, 5, 'HOUSE', 9, 1, true, 3, 2),
                                                                                                                                              (31, 'Sarajevo Vrelo Bosne Cottage', 'Quiet cottage near the park springs with easy tram access to the old town.', 76.00, 4, 'COTTAGE', 10, 1, true, 2, 1),
                                                                                                                                              (32, 'Mostar Old Bridge Guesthouse', 'Guesthouse steps from Stari Most with a terrace overlooking the river.', 84.00, 4, 'GUESTHOUSE', 11, 1, true, 2, 1),
                                                                                                                                              (33, 'Ksamil Island View Apartment', 'Apartment with a balcony facing the Ksamil islands and beach clubs.', 99.00, 3, 'APARTMENT', 12, 1, true, 2, 1),
                                                                                                                                              (34, 'Tirana Blloku Loft', 'Loft in the trendy Blloku district close to bars, galleries, and cafes.', 70.00, 3, 'LOFT', 13, 1, true, 1, 1),
                                                                                                                                              (35, 'Bansko Pirin View Chalet', 'Chalet with direct Pirin mountain views and a private sauna.', 132.00, 6, 'CABIN', 14, 1, true, 3, 2),
                                                                                                                                              (36, 'Lefkada Nydri Villa', 'Villa above Nydri with a pool, sea views, and a short drive to island ferries.', 230.00, 6, 'VILLA', 16, 1, true, 3, 2);

INSERT INTO listing_images (listing_id, image_url) VALUES
-- =========================
-- LISTING 1
-- =========================
                                                        (1, 'https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg'),
                                                        (1, 'https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg'),
                                                        (1, 'https://images.pexels.com/photos/271624/pexels-photo-271624.jpeg'),
                                                        (1, 'https://images.pexels.com/photos/276554/pexels-photo-276554.jpeg'),
                                                        (1, 'https://images.pexels.com/photos/276583/pexels-photo-276583.jpeg'),
                                                        (1, 'https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg'),
                                                        (1, 'https://images.pexels.com/photos/1457842/pexels-photo-1457842.jpeg'),
                                                        (1, 'https://images.pexels.com/photos/2104151/pexels-photo-2104151.jpeg'),
                                                        (1, 'https://images.pexels.com/photos/1454806/pexels-photo-1454806.jpeg'),
                                                        (1, 'https://images.pexels.com/photos/1743227/pexels-photo-1743227.jpeg'),

                                                    -- =========================
                                                    -- LISTING 2
                                                    -- =========================
                                                        (2, 'https://images.pexels.com/photos/271618/pexels-photo-271618.jpeg'),
                                                        (2, 'https://images.pexels.com/photos/259962/pexels-photo-259962.jpeg'),
                                                        (2, 'https://images.pexels.com/photos/276583/pexels-photo-276583.jpeg'),
                                                        (2, 'https://images.pexels.com/photos/271816/pexels-photo-271816.jpeg'),
                                                        (2, 'https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg'),
                                                        (2, 'https://images.pexels.com/photos/210604/pexels-photo-210604.jpeg'),
                                                        (2, 'https://images.pexels.com/photos/276554/pexels-photo-276554.jpeg'),
                                                        (2, 'https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg'),
                                                        (2, 'https://images.pexels.com/photos/271624/pexels-photo-271624.jpeg'),
                                                        (2, 'https://images.pexels.com/photos/1743227/pexels-photo-1743227.jpeg'),

                                                    -- =========================
                                                    -- LISTING 3
                                                    -- =========================
                                                        (3, 'https://images.pexels.com/photos/271624/pexels-photo-271624.jpeg'),
                                                        (3, 'https://images.pexels.com/photos/276583/pexels-photo-276583.jpeg'),
                                                        (3, 'https://images.pexels.com/photos/2104151/pexels-photo-2104151.jpeg'),
                                                        (3, 'https://images.pexels.com/photos/1743227/pexels-photo-1743227.jpeg'),
                                                        (3, 'https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg'),
                                                        (3, 'https://images.pexels.com/photos/259962/pexels-photo-259962.jpeg'),
                                                        (3, 'https://images.pexels.com/photos/271816/pexels-photo-271816.jpeg'),
                                                        (3, 'https://images.pexels.com/photos/210604/pexels-photo-210604.jpeg'),
                                                        (3, 'https://images.pexels.com/photos/276554/pexels-photo-276554.jpeg'),
                                                        (3, 'https://images.pexels.com/photos/1457842/pexels-photo-1457842.jpeg'),

                                                    -- =========================
                                                    -- LISTING 4
                                                    -- =========================
                                                        (4, 'https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg'),
                                                        (4, 'https://images.pexels.com/photos/276583/pexels-photo-276583.jpeg'),
                                                        (4, 'https://images.pexels.com/photos/1743227/pexels-photo-1743227.jpeg'),
                                                        (4, 'https://images.pexels.com/photos/2104151/pexels-photo-2104151.jpeg'),
                                                        (4, 'https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg'),
                                                        (4, 'https://images.pexels.com/photos/271624/pexels-photo-271624.jpeg'),
                                                        (4, 'https://images.pexels.com/photos/259962/pexels-photo-259962.jpeg'),
                                                        (4, 'https://images.pexels.com/photos/276554/pexels-photo-276554.jpeg'),
                                                        (4, 'https://images.pexels.com/photos/1457842/pexels-photo-1457842.jpeg'),
                                                        (4, 'https://images.pexels.com/photos/210604/pexels-photo-210604.jpeg'),

                                                    -- =========================
                                                    -- LISTING 5
                                                    -- =========================
                                                        (5, 'https://images.pexels.com/photos/271816/pexels-photo-271816.jpeg'),
                                                        (5, 'https://images.pexels.com/photos/276583/pexels-photo-276583.jpeg'),
                                                        (5, 'https://images.pexels.com/photos/2104151/pexels-photo-2104151.jpeg'),
                                                        (5, 'https://images.pexels.com/photos/1743227/pexels-photo-1743227.jpeg'),
                                                        (5, 'https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg'),
                                                        (5, 'https://images.pexels.com/photos/271624/pexels-photo-271624.jpeg'),
                                                        (5, 'https://images.pexels.com/photos/259962/pexels-photo-259962.jpeg'),
                                                        (5, 'https://images.pexels.com/photos/276554/pexels-photo-276554.jpeg'),
                                                        (5, 'https://images.pexels.com/photos/1457842/pexels-photo-1457842.jpeg'),
                                                        (5, 'https://images.pexels.com/photos/210604/pexels-photo-210604.jpeg'),

                                                    -- =========================
                                                    -- LISTING 6
                                                    -- =========================
                                                        (6, 'https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg'),
                                                        (6, 'https://images.pexels.com/photos/2104151/pexels-photo-2104151.jpeg'),
                                                        (6, 'https://images.pexels.com/photos/1743227/pexels-photo-1743227.jpeg'),
                                                        (6, 'https://images.pexels.com/photos/276724/pexels-photo-276724.jpeg'),
                                                        (6, 'https://images.pexels.com/photos/271624/pexels-photo-271624.jpeg'),
                                                        (6, 'https://images.pexels.com/photos/259962/pexels-photo-259962.jpeg'),
                                                        (6, 'https://images.pexels.com/photos/276583/pexels-photo-276583.jpeg'),
                                                        (6, 'https://images.pexels.com/photos/276554/pexels-photo-276554.jpeg'),
                                                        (6, 'https://images.pexels.com/photos/1457842/pexels-photo-1457842.jpeg'),
                                                        (6, 'https://images.pexels.com/photos/210604/pexels-photo-210604.jpeg'),

                                                       (7, 'https://images.pexels.com/photos/6032225/pexels-photo-6032225.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (7, 'https://images.pexels.com/photos/5490384/pexels-photo-5490384.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (7, 'https://images.pexels.com/photos/6032235/pexels-photo-6032235.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (7, 'https://images.pexels.com/photos/18123382/pexels-photo-18123382.jpeg?auto=compress&cs=tinysrgb&w=1200'),

                                                       (8, 'https://images.pexels.com/photos/19836798/pexels-photo-19836798.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (8, 'https://images.pexels.com/photos/10099318/pexels-photo-10099318.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (8, 'https://images.pexels.com/photos/6207825/pexels-photo-6207825.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (8, 'https://images.pexels.com/photos/6198661/pexels-photo-6198661.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (8, 'https://images.pexels.com/photos/259950/pexels-photo-259950.jpeg?auto=compress&cs=tinysrgb&w=1200'),

                                                       (9, 'https://images.pexels.com/photos/11266129/pexels-photo-11266129.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (9, 'https://images.pexels.com/photos/4468806/pexels-photo-4468806.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (9, 'https://images.pexels.com/photos/29923543/pexels-photo-29923543.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (9, 'https://images.pexels.com/photos/4740580/pexels-photo-4740580.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (9, 'https://images.pexels.com/photos/17069809/pexels-photo-17069809.jpeg?auto=compress&cs=tinysrgb&w=1200'),

                                                       (10, 'https://images.pexels.com/photos/6492402/pexels-photo-6492402.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (10, 'https://images.pexels.com/photos/12277956/pexels-photo-12277956.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (10, 'https://images.pexels.com/photos/6585741/pexels-photo-6585741.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (10, 'https://images.pexels.com/photos/19013521/pexels-photo-19013521.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (10, 'https://images.pexels.com/photos/15210485/pexels-photo-15210485.jpeg?auto=compress&cs=tinysrgb&w=1200'),

                                                       (11, 'https://images.pexels.com/photos/6588599/pexels-photo-6588599.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (11, 'https://images.pexels.com/photos/6447384/pexels-photo-6447384.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (11, 'https://images.pexels.com/photos/3965512/pexels-photo-3965512.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (11, 'https://images.pexels.com/photos/6636300/pexels-photo-6636300.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (11, 'https://images.pexels.com/photos/347141/pexels-photo-347141.jpeg?auto=compress&cs=tinysrgb&w=1200'),

                                                       (12, 'https://images.pexels.com/photos/6933852/pexels-photo-6933852.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (12, 'https://images.pexels.com/photos/6969870/pexels-photo-6969870.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (12, 'https://images.pexels.com/photos/5490384/pexels-photo-5490384.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (12, 'https://images.pexels.com/photos/6487949/pexels-photo-6487949.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (12, 'https://images.pexels.com/photos/356809/pexels-photo-356809.jpeg?auto=compress&cs=tinysrgb&w=1200'),

                                                       (13, 'https://images.pexels.com/photos/24807132/pexels-photo-24807132.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (13, 'https://images.pexels.com/photos/5179534/pexels-photo-5179534.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (13, 'https://images.pexels.com/photos/6312078/pexels-photo-6312078.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (13, 'https://images.pexels.com/photos/6207825/pexels-photo-6207825.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (13, 'https://images.pexels.com/photos/6436770/pexels-photo-6436770.jpeg?auto=compress&cs=tinysrgb&w=1200'),

                                                       (14, 'https://images.pexels.com/photos/4857757/pexels-photo-4857757.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (14, 'https://images.pexels.com/photos/4992465/pexels-photo-4992465.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (14, 'https://images.pexels.com/photos/4740580/pexels-photo-4740580.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (14, 'https://images.pexels.com/photos/19846350/pexels-photo-19846350.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (14, 'https://images.pexels.com/photos/18123382/pexels-photo-18123382.jpeg?auto=compress&cs=tinysrgb&w=1200'),

                                                       (15, 'https://images.pexels.com/photos/5570222/pexels-photo-5570222.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (15, 'https://images.pexels.com/photos/6032225/pexels-photo-6032225.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (15, 'https://images.pexels.com/photos/12277956/pexels-photo-12277956.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (15, 'https://images.pexels.com/photos/7045358/pexels-photo-7045358.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (15, 'https://images.pexels.com/photos/259950/pexels-photo-259950.jpeg?auto=compress&cs=tinysrgb&w=1200'),

                                                       (16, 'https://images.pexels.com/photos/6180674/pexels-photo-6180674.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (16, 'https://images.pexels.com/photos/10099318/pexels-photo-10099318.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (16, 'https://images.pexels.com/photos/3965512/pexels-photo-3965512.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (16, 'https://images.pexels.com/photos/6032235/pexels-photo-6032235.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (16, 'https://images.pexels.com/photos/15210485/pexels-photo-15210485.jpeg?auto=compress&cs=tinysrgb&w=1200'),

                                                       (17, 'https://images.pexels.com/photos/31817155/pexels-photo-31817155.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (17, 'https://images.pexels.com/photos/28991200/pexels-photo-28991200.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (17, 'https://images.pexels.com/photos/29923543/pexels-photo-29923543.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (17, 'https://images.pexels.com/photos/5490384/pexels-photo-5490384.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (17, 'https://images.pexels.com/photos/6198661/pexels-photo-6198661.jpeg?auto=compress&cs=tinysrgb&w=1200'),

                                                       (18, 'https://images.pexels.com/photos/19836798/pexels-photo-19836798.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (18, 'https://images.pexels.com/photos/6207825/pexels-photo-6207825.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (18, 'https://images.pexels.com/photos/17069809/pexels-photo-17069809.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (18, 'https://images.pexels.com/photos/19013521/pexels-photo-19013521.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (18, 'https://images.pexels.com/photos/347141/pexels-photo-347141.jpeg?auto=compress&cs=tinysrgb&w=1200'),

                                                       (19, 'https://images.pexels.com/photos/4468806/pexels-photo-4468806.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (19, 'https://images.pexels.com/photos/6447384/pexels-photo-6447384.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (19, 'https://images.pexels.com/photos/4740580/pexels-photo-4740580.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (19, 'https://images.pexels.com/photos/6585741/pexels-photo-6585741.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (19, 'https://images.pexels.com/photos/356809/pexels-photo-356809.jpeg?auto=compress&cs=tinysrgb&w=1200'),

                                                       (20, 'https://images.pexels.com/photos/6492402/pexels-photo-6492402.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (20, 'https://images.pexels.com/photos/6969870/pexels-photo-6969870.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (20, 'https://images.pexels.com/photos/12277956/pexels-photo-12277956.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (20, 'https://images.pexels.com/photos/6636300/pexels-photo-6636300.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (20, 'https://images.pexels.com/photos/18123382/pexels-photo-18123382.jpeg?auto=compress&cs=tinysrgb&w=1200'),

                                                       (21, 'https://images.pexels.com/photos/6588599/pexels-photo-6588599.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (21, 'https://images.pexels.com/photos/6312078/pexels-photo-6312078.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (21, 'https://images.pexels.com/photos/3965512/pexels-photo-3965512.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (21, 'https://images.pexels.com/photos/6487949/pexels-photo-6487949.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (21, 'https://images.pexels.com/photos/259950/pexels-photo-259950.jpeg?auto=compress&cs=tinysrgb&w=1200'),

                                                       (22, 'https://images.pexels.com/photos/30708776/pexels-photo-30708776.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (22, 'https://images.pexels.com/photos/6933852/pexels-photo-6933852.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (22, 'https://images.pexels.com/photos/5490384/pexels-photo-5490384.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (22, 'https://images.pexels.com/photos/6436770/pexels-photo-6436770.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (22, 'https://images.pexels.com/photos/15210485/pexels-photo-15210485.jpeg?auto=compress&cs=tinysrgb&w=1200'),

                                                       (23, 'https://images.pexels.com/photos/5179534/pexels-photo-5179534.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (23, 'https://images.pexels.com/photos/4992465/pexels-photo-4992465.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (23, 'https://images.pexels.com/photos/6207825/pexels-photo-6207825.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (23, 'https://images.pexels.com/photos/19846350/pexels-photo-19846350.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (23, 'https://images.pexels.com/photos/347141/pexels-photo-347141.jpeg?auto=compress&cs=tinysrgb&w=1200'),

                                                       (24, 'https://images.pexels.com/photos/4857757/pexels-photo-4857757.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (24, 'https://images.pexels.com/photos/6032225/pexels-photo-6032225.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (24, 'https://images.pexels.com/photos/4740580/pexels-photo-4740580.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (24, 'https://images.pexels.com/photos/7045358/pexels-photo-7045358.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (24, 'https://images.pexels.com/photos/356809/pexels-photo-356809.jpeg?auto=compress&cs=tinysrgb&w=1200'),

                                                       (25, 'https://images.pexels.com/photos/9209878/pexels-photo-9209878.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (25, 'https://images.pexels.com/photos/5570222/pexels-photo-5570222.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (25, 'https://images.pexels.com/photos/12277956/pexels-photo-12277956.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (25, 'https://images.pexels.com/photos/6032235/pexels-photo-6032235.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (25, 'https://images.pexels.com/photos/28965544/pexels-photo-28965544.jpeg?auto=compress&cs=tinysrgb&w=1200'),

                                                       (26, 'https://images.pexels.com/photos/6875524/pexels-photo-6875524.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (26, 'https://images.pexels.com/photos/6180674/pexels-photo-6180674.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (26, 'https://images.pexels.com/photos/10099318/pexels-photo-10099318.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (26, 'https://images.pexels.com/photos/3965512/pexels-photo-3965512.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (26, 'https://images.pexels.com/photos/6198661/pexels-photo-6198661.jpeg?auto=compress&cs=tinysrgb&w=1200'),

                                                       (27, 'https://images.pexels.com/photos/28991200/pexels-photo-28991200.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (27, 'https://images.pexels.com/photos/29923543/pexels-photo-29923543.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (27, 'https://images.pexels.com/photos/5490384/pexels-photo-5490384.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (27, 'https://images.pexels.com/photos/17069809/pexels-photo-17069809.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (27, 'https://images.pexels.com/photos/18123382/pexels-photo-18123382.jpeg?auto=compress&cs=tinysrgb&w=1200'),

                                                       (28, 'https://images.pexels.com/photos/19836798/pexels-photo-19836798.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (28, 'https://images.pexels.com/photos/6207825/pexels-photo-6207825.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (28, 'https://images.pexels.com/photos/6585741/pexels-photo-6585741.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (28, 'https://images.pexels.com/photos/19013521/pexels-photo-19013521.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (28, 'https://images.pexels.com/photos/259950/pexels-photo-259950.jpeg?auto=compress&cs=tinysrgb&w=1200'),

                                                       (29, 'https://images.pexels.com/photos/4468806/pexels-photo-4468806.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (29, 'https://images.pexels.com/photos/6447384/pexels-photo-6447384.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (29, 'https://images.pexels.com/photos/4740580/pexels-photo-4740580.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (29, 'https://images.pexels.com/photos/6636300/pexels-photo-6636300.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (29, 'https://images.pexels.com/photos/15210485/pexels-photo-15210485.jpeg?auto=compress&cs=tinysrgb&w=1200'),

                                                       (30, 'https://images.pexels.com/photos/6492402/pexels-photo-6492402.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (30, 'https://images.pexels.com/photos/6969870/pexels-photo-6969870.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (30, 'https://images.pexels.com/photos/12277956/pexels-photo-12277956.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (30, 'https://images.pexels.com/photos/6487949/pexels-photo-6487949.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (30, 'https://images.pexels.com/photos/347141/pexels-photo-347141.jpeg?auto=compress&cs=tinysrgb&w=1200'),

                                                       (31, 'https://images.pexels.com/photos/16067224/pexels-photo-16067224.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (31, 'https://images.pexels.com/photos/6588599/pexels-photo-6588599.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (31, 'https://images.pexels.com/photos/3965512/pexels-photo-3965512.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (31, 'https://images.pexels.com/photos/6436770/pexels-photo-6436770.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (31, 'https://images.pexels.com/photos/356809/pexels-photo-356809.jpeg?auto=compress&cs=tinysrgb&w=1200'),

                                                       (32, 'https://images.pexels.com/photos/6933852/pexels-photo-6933852.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (32, 'https://images.pexels.com/photos/5490384/pexels-photo-5490384.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (32, 'https://images.pexels.com/photos/19846350/pexels-photo-19846350.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (32, 'https://images.pexels.com/photos/6312078/pexels-photo-6312078.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (32, 'https://images.pexels.com/photos/18123382/pexels-photo-18123382.jpeg?auto=compress&cs=tinysrgb&w=1200'),

                                                       (33, 'https://images.pexels.com/photos/5179534/pexels-photo-5179534.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (33, 'https://images.pexels.com/photos/4992465/pexels-photo-4992465.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (33, 'https://images.pexels.com/photos/6207825/pexels-photo-6207825.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (33, 'https://images.pexels.com/photos/7045358/pexels-photo-7045358.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (33, 'https://images.pexels.com/photos/259950/pexels-photo-259950.jpeg?auto=compress&cs=tinysrgb&w=1200'),

                                                       (34, 'https://images.pexels.com/photos/4857757/pexels-photo-4857757.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (34, 'https://images.pexels.com/photos/6032225/pexels-photo-6032225.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (34, 'https://images.pexels.com/photos/4740580/pexels-photo-4740580.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (34, 'https://images.pexels.com/photos/6032235/pexels-photo-6032235.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (34, 'https://images.pexels.com/photos/15210485/pexels-photo-15210485.jpeg?auto=compress&cs=tinysrgb&w=1200'),

                                                       (35, 'https://images.pexels.com/photos/9056661/pexels-photo-9056661.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (35, 'https://images.pexels.com/photos/5570222/pexels-photo-5570222.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (35, 'https://images.pexels.com/photos/12277956/pexels-photo-12277956.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (35, 'https://images.pexels.com/photos/6198661/pexels-photo-6198661.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (35, 'https://images.pexels.com/photos/5708937/pexels-photo-5708937.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (36, 'https://images.pexels.com/photos/13034805/pexels-photo-13034805.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (36, 'https://images.pexels.com/photos/6180674/pexels-photo-6180674.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (36, 'https://images.pexels.com/photos/10099318/pexels-photo-10099318.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (36, 'https://images.pexels.com/photos/3965512/pexels-photo-3965512.jpeg?auto=compress&cs=tinysrgb&w=1200'),
                                                       (36, 'https://images.pexels.com/photos/17069809/pexels-photo-17069809.jpeg?auto=compress&cs=tinysrgb&w=1200');

INSERT INTO listing_amenities (listing_id, amenity) VALUES
                                                        (1, 'Fast Wi-Fi'),
                                                        (1, 'Free parking'),
                                                        (1, 'Garden'),
                                                        (1, 'Historic location'),
                                                        (2, 'Fast Wi-Fi'),
                                                        (2, 'Air conditioning'),
                                                        (2, 'Balcony'),
                                                        (2, 'Walkable location'),
                                                        (3, 'Fast Wi-Fi'),
                                                        (3, 'Dedicated workspace'),
                                                        (3, 'City view'),
                                                        (3, 'Air conditioning'),
                                                        (4, 'Fireplace'),
                                                        (4, 'Mountain view'),
                                                        (4, 'Free parking'),
                                                        (4, 'Heating'),
                                                        (5, 'Fast Wi-Fi'),
                                                        (5, 'Air conditioning'),
                                                        (5, 'Elevator'),
                                                        (5, 'City center'),
                                                        (6, 'Fireplace'),
                                                        (6, 'Mountain view'),
                                                        (6, 'Free parking'),
                                                        (6, 'Heating'),
                                                        (7, 'Fast Wi-Fi'),
                                                        (7, 'Air conditioning'),
                                                        (7, 'Elevator'),
                                                        (7, 'City center'),
                                                        (8, 'Fast Wi-Fi'),
                                                        (8, 'Air conditioning'),
                                                        (8, 'Balcony'),
                                                        (8, 'Walkable location'),
                                                        (9, 'Sea view'),
                                                        (9, 'Private terrace'),
                                                        (9, 'Free parking'),
                                                        (9, 'Air conditioning'),
                                                        (10, 'Historic location'),
                                                        (10, 'Fast Wi-Fi'),
                                                        (10, 'Private balcony'),
                                                        (10, 'Garden'),
                                                        (11, 'Fast Wi-Fi'),
                                                        (11, 'Dedicated workspace'),
                                                        (11, 'City view'),
                                                        (11, 'Air conditioning'),
                                                        (12, 'Fast Wi-Fi'),
                                                        (12, 'Air conditioning'),
                                                        (12, 'Elevator'),
                                                        (12, 'City center'),
                                                        (13, 'Sea view'),
                                                        (13, 'Private terrace'),
                                                        (13, 'Free parking'),
                                                        (13, 'Air conditioning'),
                                                        (14, 'Fast Wi-Fi'),
                                                        (14, 'Air conditioning'),
                                                        (14, 'Elevator'),
                                                        (14, 'City center'),
                                                        (15, 'Fast Wi-Fi'),
                                                        (15, 'Dedicated workspace'),
                                                        (15, 'City view'),
                                                        (15, 'Air conditioning'),
                                                        (16, 'Fast Wi-Fi'),
                                                        (16, 'Air conditioning'),
                                                        (16, 'Elevator'),
                                                        (16, 'City center'),
                                                        (17, 'Sea view'),
                                                        (17, 'Private terrace'),
                                                        (17, 'Free parking'),
                                                        (17, 'Air conditioning'),
                                                        (18, 'Historic location'),
                                                        (18, 'Fast Wi-Fi'),
                                                        (18, 'Private balcony'),
                                                        (18, 'Garden'),
                                                        (19, 'Fast Wi-Fi'),
                                                        (19, 'Dedicated workspace'),
                                                        (19, 'City view'),
                                                        (19, 'Air conditioning'),
                                                        (20, 'Fast Wi-Fi'),
                                                        (20, 'Air conditioning'),
                                                        (20, 'Elevator'),
                                                        (20, 'City center'),
                                                        (21, 'Fast Wi-Fi'),
                                                        (21, 'Air conditioning'),
                                                        (21, 'Balcony'),
                                                        (21, 'Walkable location'),
                                                        (22, 'Fireplace'),
                                                        (22, 'Garden'),
                                                        (22, 'Free parking'),
                                                        (22, 'Heating'),
                                                        (23, 'Fast Wi-Fi'),
                                                        (23, 'Dedicated workspace'),
                                                        (23, 'City view'),
                                                        (23, 'Air conditioning'),
                                                        (24, 'Fast Wi-Fi'),
                                                        (24, 'Air conditioning'),
                                                        (24, 'Elevator'),
                                                        (24, 'City center'),
                                                        (25, 'Fireplace'),
                                                        (25, 'Mountain view'),
                                                        (25, 'Free parking'),
                                                        (25, 'Heating'),
                                                        (26, 'Sea view'),
                                                        (26, 'Private terrace'),
                                                        (26, 'Free parking'),
                                                        (26, 'Air conditioning'),
                                                        (27, 'Fast Wi-Fi'),
                                                        (27, 'Air conditioning'),
                                                        (27, 'Elevator'),
                                                        (27, 'City center'),
                                                        (28, 'Historic location'),
                                                        (28, 'Fast Wi-Fi'),
                                                        (28, 'Private balcony'),
                                                        (28, 'Garden'),
                                                        (29, 'Fast Wi-Fi'),
                                                        (29, 'Air conditioning'),
                                                        (29, 'Balcony'),
                                                        (29, 'Walkable location'),
                                                        (30, 'Fast Wi-Fi'),
                                                        (30, 'Free parking'),
                                                        (30, 'Garden'),
                                                        (30, 'Historic location'),
                                                        (31, 'Fireplace'),
                                                        (31, 'Garden'),
                                                        (31, 'Free parking'),
                                                        (31, 'Heating'),
                                                        (32, 'Historic location'),
                                                        (32, 'Fast Wi-Fi'),
                                                        (32, 'Private balcony'),
                                                        (32, 'Garden'),
                                                        (33, 'Fast Wi-Fi'),
                                                        (33, 'Air conditioning'),
                                                        (33, 'Elevator'),
                                                        (33, 'City center'),
                                                        (34, 'Fast Wi-Fi'),
                                                        (34, 'Dedicated workspace'),
                                                        (34, 'City view'),
                                                        (34, 'Air conditioning'),
                                                        (35, 'Fireplace'),
                                                        (35, 'Mountain view'),
                                                        (35, 'Free parking'),
                                                        (35, 'Heating'),
                                                        (36, 'Sea view'),
                                                        (36, 'Private terrace'),
                                                        (36, 'Free parking'),
                                                        (36, 'Air conditioning');

INSERT INTO bookings (id, listing_id, guest_id, check_in_date, check_out_date, number_of_guests, total_price, status) VALUES
                                                                                                                          (1, 1, 2, '2026-07-10', '2026-07-14', 2, 460.00, 'CONFIRMED'),
                                                                                                                          (2, 4, 3, '2026-08-02', '2026-08-06', 4, 500.00, 'PENDING'),
                                                                                                                          (3, 9, 4, '2026-07-20', '2026-07-25', 5, 1200.00, 'CONFIRMED'),
                                                                                                                          (4, 13, 2, '2026-09-05', '2026-09-09', 3, 540.00, 'CANCELLED'),
                                                                                                                          (5, 22, 5, '2026-07-15', '2026-07-18', 3, 324.00, 'CONFIRMED'),
                                                                                                                          (6, 26, 6, '2026-08-10', '2026-08-17', 8, 1925.00, 'CONFIRMED'),
                                                                                                                          (7, 30, 2, '2026-09-01', '2026-09-04', 4, 495.00, 'PENDING'),
                                                                                                                          (8, 34, 3, '2026-07-25', '2026-07-28', 2, 210.00, 'CONFIRMED'),
                                                                                                                          (9, 36, 5, '2026-08-20', '2026-08-25', 5, 1150.00, 'CONFIRMED');

INSERT INTO reviews (id, listing_id, guest_id, rating, comment) VALUES
                                                                    (1, 1, 2, 5, 'Beautiful old town location and a clear lake view from the house.'),
                                                                    (2, 3, 3, 4, 'Clean loft, easy walk to the center, and reliable Wi-Fi.'),
                                                                    (3, 7, 4, 5, 'Excellent location inside Dubrovnik old town and very comfortable.'),
                                                                    (4, 10, 2, 5, 'The bay view in Kotor was the highlight of the trip.'),
                                                                    (5, 13, 3, 4, 'Great base for Ksamil beaches with useful parking.'),
                                                                    (6, 17, 4, 5, 'Spacious villa with a terrace made for sunset dinners.'),
                                                                    (7, 22, 5, 4, 'Peaceful cottage with an easy trail right outside the door.'),
                                                                    (8, 26, 6, 5, 'The pool and the walk to the beach made this a perfect stay.'),
                                                                    (9, 30, 2, 5, 'Loved being inside the old town walls, very central.'),
                                                                    (10, 34, 3, 4, 'Great neighborhood for evenings out and good coffee nearby.'),
                                                                    (11, 36, 5, 5, 'Villa pool and sea views were even better than the photos.');

SELECT setval('cities_id_seq', (SELECT MAX(id) FROM cities));
SELECT setval('users_id_seq', (SELECT MAX(id) FROM users));
SELECT setval('listings_id_seq', (SELECT MAX(id) FROM listings));
SELECT setval('bookings_id_seq', (SELECT MAX(id) FROM bookings));
SELECT setval('reviews_id_seq', (SELECT MAX(id) FROM reviews));